name: Auto Assign
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          # using the `org/team_slug` or `/team_slug` syntax to add git team as reviewers
          reviewers: yosraammar